### ISSUE TITLE
Minor typo in README and npm description

### ISSUE THREAD

**Issue by justincone** [ido-ofir/node-chat-server#1]
This is a tiny error, but in the README and npm description there's a small typo under the "Client" heading:

> "There is a complimentary client side module on npm..."

Should be:

> There is a **complementary** client side module on npm

"Complementary" (with an "e") means something that completes or fits together with something else, which is the intended meaning.  

More information: http://www.thewritingsite.org/complementary-vs-complimentary/

**Comment by ido-ofir** [comment]
Updated README.
thank you.
